#############################################################################
# Makefile for building: hydro
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? ??? 16 13:49:16 2013
# Project:  hydro.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile hydro.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Itemp/moc
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = temp/obj/

####### Files

SOURCES       = Main.cpp \
		Storage.cpp \
		Wizard.cpp \
		PageIntro.cpp \
		PageSpecification.cpp \
		PageSpecificationFile.cpp \
		PageSpecificationData.cpp \
		PagePrecision.cpp \
		PageIterationInfo.cpp \
		PageIteration.cpp \
		PageFinal.cpp temp/moc/moc_Wizard.cpp \
		temp/moc/moc_PageIntro.cpp \
		temp/moc/moc_PageSpecification.cpp \
		temp/moc/moc_PageSpecificationFile.cpp \
		temp/moc/moc_PageSpecificationData.cpp \
		temp/moc/moc_PagePrecision.cpp \
		temp/moc/moc_PageIterationInfo.cpp \
		temp/moc/moc_PageIteration.cpp \
		temp/moc/moc_PageFinal.cpp \
		temp/rcc/qrc_hydro.cpp
OBJECTS       = temp/obj/Main.o \
		temp/obj/Storage.o \
		temp/obj/Wizard.o \
		temp/obj/PageIntro.o \
		temp/obj/PageSpecification.o \
		temp/obj/PageSpecificationFile.o \
		temp/obj/PageSpecificationData.o \
		temp/obj/PagePrecision.o \
		temp/obj/PageIterationInfo.o \
		temp/obj/PageIteration.o \
		temp/obj/PageFinal.o \
		temp/obj/moc_Wizard.o \
		temp/obj/moc_PageIntro.o \
		temp/obj/moc_PageSpecification.o \
		temp/obj/moc_PageSpecificationFile.o \
		temp/obj/moc_PageSpecificationData.o \
		temp/obj/moc_PagePrecision.o \
		temp/obj/moc_PageIterationInfo.o \
		temp/obj/moc_PageIteration.o \
		temp/obj/moc_PageFinal.o \
		temp/obj/qrc_hydro.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hydro.pro
QMAKE_TARGET  = hydro
DESTDIR       = 
TARGET        = hydro

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hydro.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile hydro.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hydro.pro

dist: 
	@$(CHK_DIR_EXISTS) temp/obj/hydro1.0.0 || $(MKDIR) temp/obj/hydro1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/obj/hydro1.0.0/ && $(COPY_FILE) --parents Storage.h Wizard.h PageIntro.h PageSpecification.h PageSpecificationFile.h PageSpecificationData.h PagePrecision.h PageIterationInfo.h PageIteration.h PageFinal.h temp/obj/hydro1.0.0/ && $(COPY_FILE) --parents hydro.qrc temp/obj/hydro1.0.0/ && $(COPY_FILE) --parents Main.cpp Storage.cpp Wizard.cpp PageIntro.cpp PageSpecification.cpp PageSpecificationFile.cpp PageSpecificationData.cpp PagePrecision.cpp PageIterationInfo.cpp PageIteration.cpp PageFinal.cpp temp/obj/hydro1.0.0/ && (cd `dirname temp/obj/hydro1.0.0` && $(TAR) hydro1.0.0.tar hydro1.0.0 && $(COMPRESS) hydro1.0.0.tar) && $(MOVE) `dirname temp/obj/hydro1.0.0`/hydro1.0.0.tar.gz . && $(DEL_FILE) -r temp/obj/hydro1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: temp/moc/moc_Wizard.cpp temp/moc/moc_PageIntro.cpp temp/moc/moc_PageSpecification.cpp temp/moc/moc_PageSpecificationFile.cpp temp/moc/moc_PageSpecificationData.cpp temp/moc/moc_PagePrecision.cpp temp/moc/moc_PageIterationInfo.cpp temp/moc/moc_PageIteration.cpp temp/moc/moc_PageFinal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/moc/moc_Wizard.cpp temp/moc/moc_PageIntro.cpp temp/moc/moc_PageSpecification.cpp temp/moc/moc_PageSpecificationFile.cpp temp/moc/moc_PageSpecificationData.cpp temp/moc/moc_PagePrecision.cpp temp/moc/moc_PageIterationInfo.cpp temp/moc/moc_PageIteration.cpp temp/moc/moc_PageFinal.cpp
temp/moc/moc_Wizard.cpp: Wizard.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) Wizard.h -o temp/moc/moc_Wizard.cpp

temp/moc/moc_PageIntro.cpp: PageIntro.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageIntro.h -o temp/moc/moc_PageIntro.cpp

temp/moc/moc_PageSpecification.cpp: PageSpecification.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageSpecification.h -o temp/moc/moc_PageSpecification.cpp

temp/moc/moc_PageSpecificationFile.cpp: PageSpecificationFile.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageSpecificationFile.h -o temp/moc/moc_PageSpecificationFile.cpp

temp/moc/moc_PageSpecificationData.cpp: PageSpecificationData.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageSpecificationData.h -o temp/moc/moc_PageSpecificationData.cpp

temp/moc/moc_PagePrecision.cpp: PagePrecision.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PagePrecision.h -o temp/moc/moc_PagePrecision.cpp

temp/moc/moc_PageIterationInfo.cpp: PageIterationInfo.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageIterationInfo.h -o temp/moc/moc_PageIterationInfo.cpp

temp/moc/moc_PageIteration.cpp: PageIteration.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageIteration.h -o temp/moc/moc_PageIteration.cpp

temp/moc/moc_PageFinal.cpp: PageFinal.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) PageFinal.h -o temp/moc/moc_PageFinal.cpp

compiler_rcc_make_all: temp/rcc/qrc_hydro.cpp
compiler_rcc_clean:
	-$(DEL_FILE) temp/rcc/qrc_hydro.cpp
temp/rcc/qrc_hydro.cpp: hydro.qrc \
		pics/table-next.png \
		pics/table-save.png \
		pics/add.png \
		pics/save.png \
		pics/bad.png \
		pics/logo.jpg \
		pics/remove.png \
		pics/good.png \
		pics/table-new.png
	/usr/lib/qt4/bin/rcc -name hydro hydro.qrc -o temp/rcc/qrc_hydro.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

temp/obj/Main.o: Main.cpp Wizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Main.o Main.cpp

temp/obj/Storage.o: Storage.cpp Storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Storage.o Storage.cpp

temp/obj/Wizard.o: Wizard.cpp Wizard.h \
		PageIntro.h \
		PageSpecification.h \
		PageSpecificationFile.h \
		PageSpecificationData.h \
		PagePrecision.h \
		PageIterationInfo.h \
		PageIteration.h \
		PageFinal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/Wizard.o Wizard.cpp

temp/obj/PageIntro.o: PageIntro.cpp Wizard.h \
		PageIntro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageIntro.o PageIntro.cpp

temp/obj/PageSpecification.o: PageSpecification.cpp Wizard.h \
		PageSpecification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageSpecification.o PageSpecification.cpp

temp/obj/PageSpecificationFile.o: PageSpecificationFile.cpp Wizard.h \
		PageSpecificationFile.h \
		Storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageSpecificationFile.o PageSpecificationFile.cpp

temp/obj/PageSpecificationData.o: PageSpecificationData.cpp Wizard.h \
		PageSpecificationData.h \
		Storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageSpecificationData.o PageSpecificationData.cpp

temp/obj/PagePrecision.o: PagePrecision.cpp Storage.h \
		Wizard.h \
		PagePrecision.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PagePrecision.o PagePrecision.cpp

temp/obj/PageIterationInfo.o: PageIterationInfo.cpp Wizard.h \
		PageIterationInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageIterationInfo.o PageIterationInfo.cpp

temp/obj/PageIteration.o: PageIteration.cpp Wizard.h \
		PageIteration.h \
		Storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageIteration.o PageIteration.cpp

temp/obj/PageFinal.o: PageFinal.cpp Wizard.h \
		PageFinal.h \
		Storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/PageFinal.o PageFinal.cpp

temp/obj/moc_Wizard.o: temp/moc/moc_Wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_Wizard.o temp/moc/moc_Wizard.cpp

temp/obj/moc_PageIntro.o: temp/moc/moc_PageIntro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageIntro.o temp/moc/moc_PageIntro.cpp

temp/obj/moc_PageSpecification.o: temp/moc/moc_PageSpecification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageSpecification.o temp/moc/moc_PageSpecification.cpp

temp/obj/moc_PageSpecificationFile.o: temp/moc/moc_PageSpecificationFile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageSpecificationFile.o temp/moc/moc_PageSpecificationFile.cpp

temp/obj/moc_PageSpecificationData.o: temp/moc/moc_PageSpecificationData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageSpecificationData.o temp/moc/moc_PageSpecificationData.cpp

temp/obj/moc_PagePrecision.o: temp/moc/moc_PagePrecision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PagePrecision.o temp/moc/moc_PagePrecision.cpp

temp/obj/moc_PageIterationInfo.o: temp/moc/moc_PageIterationInfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageIterationInfo.o temp/moc/moc_PageIterationInfo.cpp

temp/obj/moc_PageIteration.o: temp/moc/moc_PageIteration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageIteration.o temp/moc/moc_PageIteration.cpp

temp/obj/moc_PageFinal.o: temp/moc/moc_PageFinal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/moc_PageFinal.o temp/moc/moc_PageFinal.cpp

temp/obj/qrc_hydro.o: temp/rcc/qrc_hydro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/obj/qrc_hydro.o temp/rcc/qrc_hydro.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

